server:
  port: 8000
spring:
  application:
    name: canalcar
eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka
  instance:
    hostname: ${HOST}
#Si no, se registra en Eureka con el nombre de la imagen Docker, y el servicio cliente no lo encuentra.
#HOST será el nombre con el que se registre la imagen Docker en Eureka