server:
  port: 9000
spring:
  application:
    name: servidor-gateway   
  cloud: 
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*" 
      routes:
      - id: servProductos #Id de la ruta, QUE NO SE USA EN NINGÚN SITIO
        uri: lb://productos #lb=loadBalanced, esto activa Ribbon
        predicates:
          - Path=/sproductos/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://servicio-productos)
        filters:
          - RewritePath=/sproductos/*, / #Indica que a la url de "uri" le sustituye /sproductos/ por /, y deja el resto de la petición        
      - id: servPedidos
        uri: lb://pedidos 
        predicates:
          - Path=/spedidos/**
        filters:
          - RewritePath=/spedidos/*, /
      - id: libreria
        uri: lb://libreria 
        predicates:
          - Path=/slibreria/**
        filters:
          - RewritePath=/slibreria/*, /  
      - id: tienda
        uri: lb://tienda 
        predicates:
          - Path=/stienda/**
        filters:
          - RewritePath=/stienda/*, /  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka